apiVersion: v1
kind: ConfigMap
metadata:
  name: ${SERVICE_NAME}-config
  namespace: ${NAMESPACE}
data:
  PACKAGES_ENVIRONMENT : "preprod"
  HPKP_MAX_AGE : "86400"
  REDISCLOUD_URL : "redis://ignore:mjh%2FSYWam86tgm9DO3WSfn1tgcUD4ipdDKn03%2B5mplo%3D@div-redis-aat.redis.cache.windows.net:6380?tls"
  BASE_URL : "https://div-dn-aat.service.core-compute-aat.internal"
  REFORM_ENVIRONMENT : "aat"
  APPLICATION_INSIGHTS_IKEY : "5e401c0a-0633-4671-a0e7-e3cd538abd7a"
  IDAM_APP_HEALHCHECK_URL : "https://preprod-idamapi.reform.hmcts.net:3511/health"
  PACKAGES_VERSION : "3.0.0"
  DEPLOYMENT_ENV : "preprod"
  GOOGLE_ANALYTICS_ID : "TBD"
  IDAM_LOGIN_URL : "https://idam.preprod.ccidam.reform.hmcts.net/login"
  RATE_LIMITER_EXPIRE : "3600000"
  SLOT : "PRODUCTION"
  SERVICE_NAME : "divorce-decree-nisi-frontend"
  PACKAGES_NAME : "frontend"
  REFORM_SERVICE_NAME : "dn"
  IDAM_AUTHENTICATION_HEALHCHECK_URL : "https://idam.preprod.ccidam.reform.hmcts.net/health"
  GOOGLE_ANALYTICS_TRACKING_URL : "http://www.google-analytics.com/collect"
  RATE_LIMITER_ENABLED : "0"
  NODE_ENV : "production"
  HPKP_SHAS : "Naw+prhcXSIkbtYJ0t7vAD+Fc92DWL9UZevVfWBvids=,klO23nT2ehFDXCfx3eHTDRESMz3asj1muO+4aIdjiuY=,grX4Ta9HpZx6tSHkmCrvpApTQGo67CYDnvprLg5yRME="
  IDAM_API_URL : "https://preprod-idamapi.reform.hmcts.net:3511"
  REFORM_TEAM : "div"
  PACKAGES_PROJECT : "divorce"
  RATE_LIMITER_TOTAL : "3600"
  APPINSIGHTS_INSTRUMENTATIONKEY : "5e401c0a-0633-4671-a0e7-e3cd538abd7a"