dependencies:
  - name: nodejs
    version: 2.0.1
    repository: '@hmctspublic'
  - name: redis
    version: "10.0.0"
    repository: "https://charts.bitnami.com/bitnami"
    tags:
      - pr
  - name: idam-pr
    version: 2.2.6
    repository: '@hmctspublic'
    tags:
      - idam-pr
