idam-pr:
  redirect_uris:
    divorce:
      - https://${SERVICE_FQDN}/authenticated

nodejs:
    environment:
        BASE_URL: "https://${SERVICE_NAME}.service.core-compute-preview.internal"
        PUBLIC_HOSTNAME: "https://${SERVICE_NAME}.service.core-compute-preview.internal"
        FEATURE_WEBCHAT: "false"
        FEATURE_ANTENNA_WEBCHAT: "true"
        PETITIONER_FRONTEND_URL: "https://petitioner-frontend-aks.aat.platform.hmcts.net"
        FEATURE_ANTENNA_WEBCHAT_USER_ATTRIBUTE: "true"
        ANTENNA_WEBCHAT_URL: "webchat.training.ctsc.hmcts.net"
        ANTENNA_WEBCHAT_SERVICE: "Testing"

    # Don't modify below here
    image: ${IMAGE_NAME}
    ingressHost: ${SERVICE_FQDN}
    keyVaults:
        div:
            secrets:
              - session-secret
              - redis-secret
              - idam-secret

tags:
  idam-pr: true
  pr: false
