idam-pr:
  redirect_uris:
    divorce:
      - https://${SERVICE_FQDN}/authenticated

nodejs:
    environment:
        REDISCLOUD_URL: "redis://${SERVICE_NAME}-redis-master:6379"
        BASE_URL: "https://${SERVICE_NAME}.preview.platform.hmcts.net"
        PUBLIC_HOSTNAME: "https://${SERVICE_NAME}.preview.platform.hmcts.net"
        FEATURE_WEBCHAT: "false"
        FEATURE_ANTENNA_WEBCHAT: "true"
        PETITIONER_FRONTEND_URL: "https://petitioner-frontend-aks.aat.platform.hmcts.net"
        FEATURE_ANTENNA_WEBCHAT_USER_ATTRIBUTE: "true"
        ANTENNA_WEBCHAT_URL: "webchat.pp.ctsc.hmcts.net"
        ANTENNA_WEBCHAT_SERVICE: "Divorce"
        ANTENNA_WEBCHAT_VERSION: "1"
        ANTENNA_WEBCHAT_AVAILABILITY_DEBUG: "true"
        FEATURE_ANTENNA_WEBCHAT_AVAILABILITY_TOGGLE: "true"
        FEATURE_DYNATRACE: "false"
        FEATURE_PING_REDIS: "true"

    # Don't modify below here
    image: ${IMAGE_NAME}
    ingressHost: ${SERVICE_FQDN}
    keyVaults:
        div:
            secrets:
              - session-secret
              - redis-secret
              - idam-secret

redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: false
  serviceAccount:
    create: false
    name: "divorce"
    automountServiceAccountToken: true

tags:
  idam-pr: true
  pr: true
