idam-pr:
  redirect_uris:
    divorce:
      - https://${SERVICE_FQDN}/authenticated

nodejs:
    aadIdentityName:
    environment:
        REDISCLOUD_URL: "redis://${SERVICE_NAME}-redis-master:6379"
        BASE_URL: "https://${SERVICE_NAME}.service.core-compute-preview.internal"
        PUBLIC_HOSTNAME: "https://${SERVICE_NAME}.service.core-compute-preview.internal"
        FEATURE_WEBCHAT: "true"
        FEATURE_AWAITING_CLARIFICATION: "true"
        FEATURE_DN_IS_REFUSED: "true"
    # Don't modify below here
    image: ${IMAGE_NAME}
    ingressHost: ${SERVICE_FQDN}
    keyVaults:
        div:
            secrets:
              - session-secret
              - redis-secret
              - idam-secret

tags:
  idam-pr: true
  pr: true
