environment: DEPLOYMENT_ENV
NODE_ENV: NODE_ENV

node:
  port: PORT
  baseUrl: BASE_URL

session:
  secret: SESSION_SECRET

tests:
  functional:
    waitForTimeout: FUNCTIONAL_WAIT_FOR_TIMEOUT_VALUE
    waitForAction: FUNCTIONAL_WAIT_FOR_ACTION_VALUE
    outputDir: FUNCTIONAL_OUTPUT_DIR
    url: TEST_URL
    idam:
      idamTestApiProxy: FUNCTIONAL_IDAM_PROXY
      idamTestProxyByPass: FUNCTIONAL_IDAM_SERVER
      idamTestUsername: FUNCTIONAL_IDAM_USERNAME
      idamTestPassword: FUNCTIONAL_IDAM_PASSWORD
      idamTestForename: IDAM_TEST_FORENAME
      idamTestSurname: IDAM_TEST_SURNAME
      idamTestUserGroup: IDAM_TEST_USER_GROUP
      idamTestLevelOfAccess: IDAM_TEST_LEVEL_OF_ACCESS
      idamTestSupportCreateAccountEndpoint: IDAM_TEST_SUPPORT_CREATE_ACCOUNT_ENDPOINT

ssl:
  hpkp:
    maxAge: HPKP_MAX_AGE
    sha256s: HPKP_SHAS

services:
  redis:
    url: REDISCLOUD_URL
    useSSL: USE_SSL
    encryptionAtRestKey: REDIS_ENCRYPTION_SECRET
  idam:
    apiHealth: IDAM_APP_HEALHCHECK_URL
    authenticationHealth: IDAM_AUTHENTICATION_HEALHCHECK_URL
    apiUrl: IDAM_API_URL
    secret: IDAM_SECRET
    loginUrl: IDAM_LOGIN_URL
    clientId: IDAM_CLIENT_ID
  googleAnalytics:
    id: GOOGLE_ANALYTICS_ID
    trackingUrl: GOOGLE_ANALYTICS_TRACKING_URL
  applicationInsights:
    instrumentationKey: APPINSIGHTS_INSTRUMENTATIONKEY
  evidenceManagmentClient:
    health: EVIDENCE_MANAGEMENT_CLIENT_API_HEALTHCHECK_URL
    url: EVIDENCE_MANAGEMENT_CLIENT_API_URL
    uploadEndpoint: EVIDENCE_MANAGEMENT_CLIENT_API_UPLOAD_ENDPOINT
  rateLimiter:
    total: RATE_LIMITER_TOTAL
    expire: RATE_LIMITER_EXPIRE
    enabled: RATE_LIMITER_ENABLED
  orchestrationService:
    getCaseUrl: ORCHESTRATION_SERVICE_GET_PETITION_URL
    submitCaseUrl: ORCHESTRATION_SERVICE_POST_PETITION_URL
    health: ORCHESTRATION_SERVICE_HEALTH_URL
    draftEndpoint: ORCHESTRATION_SERVICE_DRAFT_ENDPOINT
  petitionerFrontend:
    url: PETITIONER_FRONTEND_URL

journey:
  timeoutDelay: JOURNEY_TIMEOUT_DELAY
